/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2026-04-17 04:35:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AdminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1769592207882L));
    _jspx_dependants.put("jar:file:/D:/sts-4.19.1.RELEASE/Project2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudentPerfomancePredictionSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Admin Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-family:'Poppins',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ===== SIDEBAR ===== */\r\n");
      out.write(".sidebar{\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    width:250px;\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    background:rgba(20,30,48,0.9);\r\n");
      out.write("    backdrop-filter:blur(10px);\r\n");
      out.write("    color:white;\r\n");
      out.write("    padding-top:20px;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("    z-index:1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar h3{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    margin-bottom:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    gap:10px;\r\n");
      out.write("    padding:15px 25px;\r\n");
      out.write("    color:#ccc;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("    border-left:4px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover{\r\n");
      out.write("    background:rgba(255,255,255,0.08);\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    border-left:4px solid #00c6ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ACTIVE */\r\n");
      out.write(".sidebar a.active{\r\n");
      out.write("    background:rgba(0,198,255,0.15);\r\n");
      out.write("    border-left:4px solid #00c6ff;\r\n");
      out.write("    color:#fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ===== OVERLAY ===== */\r\n");
      out.write(".overlay{\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    background:rgba(0,0,0,0.6);\r\n");
      out.write("    display:none;\r\n");
      out.write("    z-index:999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay.active{\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ===== TOPBAR ===== */\r\n");
      out.write(".topbar{\r\n");
      out.write("    margin-left:250px;\r\n");
      out.write("    height:65px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    padding:0 20px;\r\n");
      out.write("    background:rgba(255,255,255,0.9);\r\n");
      out.write("    backdrop-filter:blur(10px);\r\n");
      out.write("    box-shadow:0 2px 10px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-btn{\r\n");
      out.write("    display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ===== MAIN ===== */\r\n");
      out.write(".main-content{\r\n");
      out.write("    margin-left:250px;\r\n");
      out.write("    height:calc(100vh - 65px);\r\n");
      out.write("    overflow-y:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* HERO */\r\n");
      out.write(".header-image{\r\n");
      out.write("    height:100%;\r\n");
      out.write("    background:\r\n");
      out.write("    linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.7)),\r\n");
      out.write("    url('https://images.unsplash.com/photo-1523240795612-9a054b0db644');\r\n");
      out.write("\r\n");
      out.write("    background-size:cover;\r\n");
      out.write("    background-position:center;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-text h1{\r\n");
      out.write("    font-size:50px;\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-text p{\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("    color:#ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ===== MOBILE ===== */\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write("    .sidebar{\r\n");
      out.write("        left:-250px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar.show{\r\n");
      out.write("        left:0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .topbar{\r\n");
      out.write("        margin-left:0;\r\n");
      out.write("        justify-content:space-between;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-content{\r\n");
      out.write("        margin-left:0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu-btn{\r\n");
      out.write("        display:block;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"overlay\" onclick=\"toggleSidebar()\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- SIDEBAR -->\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <h3><i class=\"bi bi-speedometer2\"></i> Admin</h3>\r\n");
      out.write("\r\n");
      out.write("    <a class=\"active\"><i class=\"bi bi-house-door\"></i> Dashboard</a>\r\n");
      out.write("    <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"><i class=\"bi bi-person-plus\"></i> Add User</a>\r\n");
      out.write("    <a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"><i class=\"bi bi-person-video3\"></i> Teachers</a>\r\n");
      out.write("    <a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"><i class=\"bi bi-mortarboard\"></i> Students</a>\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\"><i class=\"bi bi-box-arrow-right\"></i> Logout</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- TOPBAR -->\r\n");
      out.write("<div class=\"topbar\">\r\n");
      out.write("    <button class=\"btn btn-dark menu-btn\" onclick=\"toggleSidebar()\">\r\n");
      out.write("        <i class=\"bi bi-list\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <h5 class=\"m-0 fw-bold\">Admin Dashboard</h5>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"header-image\">\r\n");
      out.write("        <div class=\"header-text\">\r\n");
      out.write("            <h1>Welcome Admin</h1>\r\n");
      out.write("            <p>Manage Users, Teachers & Students Easily</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function toggleSidebar(){\r\n");
      out.write("    document.querySelector(\".sidebar\").classList.toggle(\"show\");\r\n");
      out.write("    document.querySelector(\".overlay\").classList.toggle(\"active\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/view/AdminDashboard.jsp(167,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/admin/addUser");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/view/AdminDashboard.jsp(168,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/admin/viewUsers/TEACHER");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/view/AdminDashboard.jsp(169,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/admin/viewUsers/STUDENT");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
