/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2026-04-14 05:29:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>GradeSense | Student Performance Prediction</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* BODY */\r\n");
      out.write("body{\r\n");
      out.write("margin:0;\r\n");
      out.write("font-family:'Segoe UI',sans-serif;\r\n");
      out.write("background:#f8fafc;\r\n");
      out.write("color:#1e293b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* NAVBAR */\r\n");
      out.write(".navbar{\r\n");
      out.write("background:#ffffff !important;\r\n");
      out.write("border-bottom:1px solid #e2e8f0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand{\r\n");
      out.write("font-size:22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* FIX TOGGLE ICON */\r\n");
      out.write(".navbar-toggler{\r\n");
      out.write("border:1px solid #0f172a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler-icon{\r\n");
      out.write("background-image:url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%230f172a' viewBox='0 0 30 30'%3e%3cpath stroke='rgba(15,23,42,0.9)' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CAROUSEL */\r\n");
      out.write(".carousel-item img{\r\n");
      out.write("height:85vh;\r\n");
      out.write("object-fit:cover;\r\n");
      out.write("filter:brightness(60%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption{\r\n");
      out.write("bottom:25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h1{\r\n");
      out.write("font-size:42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption p{\r\n");
      out.write("font-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SECTION */\r\n");
      out.write("section{\r\n");
      out.write("padding:70px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CARD */\r\n");
      out.write(".card{\r\n");
      out.write("border:1px solid #e2e8f0;\r\n");
      out.write("border-radius:12px;\r\n");
      out.write("transition:0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover{\r\n");
      out.write("transform:translateY(-5px);\r\n");
      out.write("box-shadow:0 10px 25px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CONTACT */\r\n");
      out.write(".contact-box{\r\n");
      out.write("background:white;\r\n");
      out.write("padding:25px;\r\n");
      out.write("border-radius:12px;\r\n");
      out.write("border:1px solid #e2e8f0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* FOOTER */\r\n");
      out.write("footer{\r\n");
      out.write("background:#0f172a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= MOBILE ================= */\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write(".navbar-brand{\r\n");
      out.write("font-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-item img{\r\n");
      out.write("height:60vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption{\r\n");
      out.write("bottom:20%;\r\n");
      out.write("padding:0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h1{\r\n");
      out.write("font-size:22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption p{\r\n");
      out.write("font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("padding:40px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#about .row{\r\n");
      out.write("flex-direction:column-reverse;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#about img{\r\n");
      out.write("margin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contact .row{\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contact img{\r\n");
      out.write("height:250px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("font-size:13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg sticky-top\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<a class=\"navbar-brand fw-bold\">GradeSense</a>\r\n");
      out.write("\r\n");
      out.write("<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#menu\">\r\n");
      out.write("<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<div class=\"collapse navbar-collapse\" id=\"menu\">\r\n");
      out.write("<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\"><a class=\"nav-link\" href=\"#home\">Home</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a class=\"nav-link\" href=\"#about\">About</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a class=\"nav-link\" href=\"#feature\">Features</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a class=\"nav-link\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item ms-lg-3 mt-2 mt-lg-0\">\r\n");
      out.write("<a href=\"login\" class=\"btn btn-dark btn-sm\">Login</a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- SLIDER -->\r\n");
      out.write("<div id=\"home\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"carousel-inner\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"carousel-item active\">\r\n");
      out.write("<img src=\"https://images.unsplash.com/photo-1523240795612-9a054b0db644\" class=\"d-block w-100\">\r\n");
      out.write("<div class=\"carousel-caption\">\r\n");
      out.write("<h1>Student Performance Prediction</h1>\r\n");
      out.write("<p>Smart insights for better academic results</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"carousel-item\">\r\n");
      out.write("<img src=\"https://images.unsplash.com/photo-1509062522246-3755977927d7\" class=\"d-block w-100\">\r\n");
      out.write("<div class=\"carousel-caption\">\r\n");
      out.write("<h1>Track & Improve Student Growth</h1>\r\n");
      out.write("<p>Analyze performance easily</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ABOUT -->\r\n");
      out.write("<section id=\"about\" class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6\">\r\n");
      out.write("<h2 class=\"fw-bold mb-3\">About System</h2>\r\n");
      out.write("<p>This system helps teachers analyze student data and predict performance.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6\">\r\n");
      out.write("<img src=\"https://images.unsplash.com/photo-1588072432836-e10032774350\"\r\n");
      out.write("class=\"img-fluid rounded shadow\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- FEATURES -->\r\n");
      out.write("<section id=\"feature\" class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"fw-bold mb-5\">Features</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("<div class=\"card p-4\">\r\n");
      out.write("<i class=\"fa-solid fa-chart-line fa-2x mb-3 text-dark\"></i>\r\n");
      out.write("<h5>Performance Analysis</h5>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("<div class=\"card p-4\">\r\n");
      out.write("<i class=\"fa-solid fa-brain fa-2x mb-3 text-dark\"></i>\r\n");
      out.write("<h5>Smart Prediction</h5>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("<div class=\"card p-4\">\r\n");
      out.write("<i class=\"fa-solid fa-user-graduate fa-2x mb-3 text-dark\"></i>\r\n");
      out.write("<h5>Dashboard</h5>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- CONTACT -->\r\n");
      out.write("<section id=\"contact\" class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"text-center fw-bold mb-5\">Contact Us</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6 mb-4\">\r\n");
      out.write("<img src=\"https://images.unsplash.com/photo-1521791136064-7986c2920216\"\r\n");
      out.write("class=\"img-fluid rounded shadow w-100\" style=\"height:420px; object-fit:cover;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6\">\r\n");
      out.write("<div class=\"contact-box\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/saveContact\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" name=\"name\" placeholder=\"Full Name\" class=\"form-control mb-3\" required>\r\n");
      out.write("<input type=\"email\" name=\"email\" placeholder=\"Email Address\" class=\"form-control mb-3\" required>\r\n");
      out.write("<input type=\"text\" name=\"phone\" placeholder=\"Phone Number\" class=\"form-control mb-3\" required>\r\n");
      out.write("\r\n");
      out.write("<textarea name=\"message\" placeholder=\"Your Message\" class=\"form-control mb-3\" rows=\"4\" required></textarea>\r\n");
      out.write("\r\n");
      out.write("<button class=\"btn btn-dark\">\r\n");
      out.write("<i class=\"fa-solid fa-paper-plane\"></i> Send Message\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- FOOTER -->\r\n");
      out.write("<footer class=\"text-white text-center p-3 mt-5\">\r\n");
      out.write("<p class=\"mb-0\">© 2026 GradeSense | All Rights Reserved</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
