/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2026-04-09 09:46:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    background:linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)),\r\n");
      out.write("    url('https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1600&q=80') no-repeat center/cover;\r\n");
      out.write("    font-family:'Segoe UI',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Login Card */\r\n");
      out.write(".login-box{\r\n");
      out.write("    width:360px;\r\n");
      out.write("    padding:35px;\r\n");
      out.write("    border-radius:18px;\r\n");
      out.write("    backdrop-filter:blur(15px);\r\n");
      out.write("    background:rgba(255,255,255,0.12);\r\n");
      out.write("    box-shadow:0 10px 40px rgba(0,0,0,0.4);\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Title */\r\n");
      out.write(".login-box h3{\r\n");
      out.write("    font-weight:600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Input group */\r\n");
      out.write(".input-group-text{\r\n");
      out.write("    background:rgba(255,255,255,0.2);\r\n");
      out.write("    border:none;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control{\r\n");
      out.write("    background:rgba(255,255,255,0.2) !important;\r\n");
      out.write("    border:none !important;\r\n");
      out.write("    color:white !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control::placeholder{\r\n");
      out.write("    color:#ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Select */\r\n");
      out.write("select{\r\n");
      out.write("    background:rgba(255,255,255,0.2) !important;\r\n");
      out.write("    color:white !important;\r\n");
      out.write("    border:none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select option{\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button */\r\n");
      out.write(".login-btn{\r\n");
      out.write("    background:#facc15;\r\n");
      out.write("    border:none;\r\n");
      out.write("    font-weight:500;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover{\r\n");
      out.write("    background:#eab308;\r\n");
      out.write("    transform:translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Bottom links */\r\n");
      out.write(".bottom-links a{\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-links a:hover{\r\n");
      out.write("    text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media(max-width:500px){\r\n");
      out.write("    .login-box{\r\n");
      out.write("        width:90%;\r\n");
      out.write("        padding:25px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"login-box\">\r\n");
      out.write("\r\n");
      out.write("    <h3 class=\"text-center mb-4\">Login</h3>\r\n");
      out.write("\r\n");
      out.write("    <!-- OPTIONAL ERROR -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"doLogin\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("        <!-- EMAIL -->\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("            <span class=\"input-group-text\">\r\n");
      out.write("                <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <input type=\"email\" name=\"email\" placeholder=\"Enter Email\"\r\n");
      out.write("            class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- PASSWORD -->\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("            <span class=\"input-group-text\">\r\n");
      out.write("                <i class=\"fa-solid fa-lock\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("            placeholder=\"Enter Password\" class=\"form-control\" required>\r\n");
      out.write("\r\n");
      out.write("            <!-- SHOW PASSWORD -->\r\n");
      out.write("            <span class=\"input-group-text\" onclick=\"togglePassword()\" style=\"cursor:pointer;\">\r\n");
      out.write("                <i class=\"fa-solid fa-eye\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ROLE -->\r\n");
      out.write("        <select name=\"role\" class=\"form-control mb-3\" required>\r\n");
      out.write("            <option value=\"\">Select Role</option>\r\n");
      out.write("            <option value=\"TEACHER\">Teacher</option>\r\n");
      out.write("            <option value=\"STUDENT\">Student</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <!-- LOGIN BUTTON -->\r\n");
      out.write("        <button class=\"btn login-btn w-100 mb-3\">Login</button>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- LINKS -->\r\n");
      out.write("    <div class=\"bottom-links text-center\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"mt-2\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">← Back to Home</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("function togglePassword(){\r\n");
      out.write("    var x = document.getElementById(\"password\");\r\n");
      out.write("    if(x.type === \"password\"){\r\n");
      out.write("        x.type = \"text\";\r\n");
      out.write("    } else {\r\n");
      out.write("        x.type = \"password\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
