/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2026-04-14 05:12:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TeacherDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Teacher Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* GLOBAL */\r\n");
      out.write("body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-family:'Segoe UI',sans-serif;\r\n");
      out.write("    background:#0f172a;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SIDEBAR */\r\n");
      out.write(".sidebar{\r\n");
      out.write("    width:250px;\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    background:linear-gradient(180deg,#1e293b,#0f172a);\r\n");
      out.write("    padding-top:20px;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("    z-index:1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* HIDDEN (MOBILE DEFAULT) */\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("    .sidebar{\r\n");
      out.write("        left:-250px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SHOW SIDEBAR */\r\n");
      out.write(".sidebar.show{\r\n");
      out.write("    left:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar h3{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    margin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    gap:10px;\r\n");
      out.write("    padding:12px 20px;\r\n");
      out.write("    color:#cbd5f5;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover{\r\n");
      out.write("    background:#1d4ed8;\r\n");
      out.write("    color:white;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* OVERLAY */\r\n");
      out.write(".overlay{\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    background:rgba(0,0,0,0.5);\r\n");
      out.write("    display:none;\r\n");
      out.write("    z-index:999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay.active{\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* TOPBAR */\r\n");
      out.write(".topbar{\r\n");
      out.write("    margin-left:250px;\r\n");
      out.write("    height:60px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:space-between;\r\n");
      out.write("    padding:0 20px;\r\n");
      out.write("    background:#1e293b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("    .topbar{\r\n");
      out.write("        margin-left:0;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* MAIN */\r\n");
      out.write(".main{\r\n");
      out.write("    margin-left:250px;\r\n");
      out.write("    padding:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("    .main{\r\n");
      out.write("        margin-left:0;\r\n");
      out.write("        padding:15px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CARDS */\r\n");
      out.write(".card{\r\n");
      out.write("    border:none;\r\n");
      out.write("    border-radius:18px;\r\n");
      out.write("    background:rgba(255,255,255,0.05);\r\n");
      out.write("    backdrop-filter:blur(12px);\r\n");
      out.write("    color:white;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover{\r\n");
      out.write("    transform:translateY(-6px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ICON */\r\n");
      out.write(".icon-box{\r\n");
      out.write("    font-size:30px;\r\n");
      out.write("    margin-bottom:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* BUTTON */\r\n");
      out.write(".btn-custom{\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- OVERLAY -->\r\n");
      out.write("<div class=\"overlay\" onclick=\"toggleSidebar()\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- SIDEBAR -->\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <h3>🎓 Teacher</h3>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/addPerformance\">\r\n");
      out.write("        <i class=\"fa-solid fa-chart-line\"></i> Add Prediction\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/viewPerformance\">\r\n");
      out.write("        <i class=\"fa-solid fa-users\"></i> View Students\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/enquiry\">\r\n");
      out.write("        <i class=\"fa-solid fa-envelope\"></i> Enquiry\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">\r\n");
      out.write("        <i class=\"fa-solid fa-right-from-bracket\"></i> Logout\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- TOPBAR -->\r\n");
      out.write("<div class=\"topbar\">\r\n");
      out.write("\r\n");
      out.write("    <button class=\"btn btn-primary d-md-none\" onclick=\"toggleSidebar()\">\r\n");
      out.write("        <i class=\"fa fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <h5>Dashboard</h5>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"mb-4\">Welcome Teacher 👋</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("            <div class=\"card p-4 text-center\">\r\n");
      out.write("                <div class=\"icon-box text-warning\">\r\n");
      out.write("                    <i class=\"fa-solid fa-plus\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h4>Add Student</h4>\r\n");
      out.write("                <p>Create new student record</p>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/addPerformance\" class=\"btn btn-warning btn-custom\">Open</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("            <div class=\"card p-4 text-center\">\r\n");
      out.write("                <div class=\"icon-box text-info\">\r\n");
      out.write("                    <i class=\"fa-solid fa-eye\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h4>View Students</h4>\r\n");
      out.write("                <p>See all records</p>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/viewPerformance\" class=\"btn btn-info btn-custom\">Open</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("            <div class=\"card p-4 text-center\">\r\n");
      out.write("                <div class=\"icon-box text-secondary\">\r\n");
      out.write("                    <i class=\"fa-solid fa-comments\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h4>Enquiry</h4>\r\n");
      out.write("                <p>Student messages</p>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/teacher/enquiry\" class=\"btn btn-secondary btn-custom\">Open</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("function toggleSidebar(){\r\n");
      out.write("    document.querySelector(\".sidebar\").classList.toggle(\"show\");\r\n");
      out.write("    document.querySelector(\".overlay\").classList.toggle(\"active\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
