spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/SpringBootProjects
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format-sql: true
  
